name: deadline

on: workflow_dispatch
#  schedule:
#    - cron: '0 7 * * *'

env:
  MAIL: ${{ secrets.MAIL }}
  PASSWORD_GIT: ${{ secrets.PASSWORD_GIT }}
  PASSWORD_MAIL: ${{ secrets.PASSWORD_MAIL }}
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  run_script:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    name: run script
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout_repo
        uses: actions/checkout@v3
      - name: cache
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'
      - name: install deps
        run: |
          pip install -r requirements.txt
      - name: Run script main
        run: python main.py


